openapi: 3.0.3
info:
    title: Swagger Songs API
    description: |-
      API for artist songs
    license: 
      name: Apache 2.0
    version: 0.0.1
tags:
  - name: songs
    description: Artist songs
paths:
    /songs/{artist}:
        get:
            tags:
              - songs
            summary: Get songs by artist
            description: returns list of artist songs
            operationId: getSongsByArtist
            parameters:
              - name: artist
                in: path
                description: Name of artist
                required: true
                schema:
                    type: string
                    default: ed-sheeran
            responses:
              200:
                description: OK
                headers:
                  Access-Control-Allow-Origin:
                    schema: 
                      type: string
                      default: "*"
                    description: "*"
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/Songs'
components:
  schemas:
    Songs:
      type: array
      items:
        type: string
